config/routes.rb
Exam20472519::Application.routes.draw do
  resources :employees do

  collection do
           get 'saveToDisk'
         end
       end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :name, :rate

  validates :rate, :numericality =>  {:greater_than_or_equal_to => 7.25}






  class << self
    def save_to_disk
      employees = Employee.all
      fname = "#{Rails.root}/test.txt"
      File.open(fname,mode="a") do |f|
        employees.each do |e|
          f.puts e.name + " , " + e.rate.to_s
        end
      end
    end
    handle_asynchronously :save_to_disk
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json

  def index
    @employees = Employee.all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  def saveToDisk
    employee = Employee.save_to_disk
    redirect_to employees_path

    end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for @employee, :validate => true do |f| %>

  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.text_field :rate %>







  </div>
  <div class="actions">
    <%= f.submit %>

    <%= javascript_include_tag "validation" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>



<table>
  <tr>
    <th>Name</th>
    <th>Rate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>
    <td><%= employee.name %></td>
    <td><%= employee.rate %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>

  </tr>
<% end %>
</table>

<br />


<%= link_to 'New Employee', new_employee_path %>
<%= link_to 'Save to disk', saveToDisk_employees_url%>

app/views/employees/new.html.erb
<h1>New employee</h1>


<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/saveToDisk.html.erb
<b>Hello world</b>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Rate:</b>
  <%= @employee.rate %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exam20472519</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", "rails.validations" %>

  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>